
export default {
  SET_PREFECTURE: 'SET_PREFECTURE',
  SET_SEARCH_MODE: 'SET_SEARCH_MODE',
  SET_QUERY_PARAMS: 'SET_QUERY_PARAMS',
  REQUEST_SEARCH_API: 'REQUEST_SEARCH_API',
  RECEIVE_SEARCH_API_RESPONSE: 'RECEIVE_SEARCH_API_RESPONSE'
}
